name = "ROMEO"
uuid = "1ea8258b-a15d-4adb-ad20-01632f467a84"
authors = ["Korbinian Eckstein", "Barbara Dymerska"]
version = "1.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ArgParse = "1"
MriResearchTools = "2.0"
StatsBase = "0.25 - 0.34"
julia = "1.6"

[extensions]
RomeoApp = ["MriResearchTools", "ArgParse"]

[weakdeps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
