name = "ROMEO"
uuid = "1ea8258b-a15d-4adb-ad20-01632f467a84"
authors = ["Korbinian Eckstein", "Barbara Dymerska"]
version = "0.2.9"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.25 - 0.33"
julia = "1.5"
